on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Compile OWID Script
        run: |
          Rscript -e 'rmarkdown::render("./Scripts/oxford.Rmd")'

      - name: Commit results
        run: |
          git config --local user.name "inception-labs-bot"
          git config --local user.email "inception-labs-bot@users.noreply.github.com"
          git commit -a -m 'Daily update of data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
